CREATE EXTENSION IF NOT EXISTS pg_trgm;

CREATE TABLE actors (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  token TEXT NOT NULL UNIQUE,
  type TEXT NOT NULL CHECK (type IN ('user', 'agent')),
  name TEXT NOT NULL,
  email TEXT UNIQUE,
  username TEXT,
  settings JSONB NOT NULL DEFAULT '{}',
  provider TEXT,
  models JSONB NOT NULL DEFAULT '[]',
  metadata JSONB NOT NULL DEFAULT '{}',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE traits (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  token TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL UNIQUE,
  description TEXT,
  tools JSONB NOT NULL DEFAULT '[]',
  namespaces JSONB NOT NULL DEFAULT '[]',
  access TEXT NOT NULL DEFAULT 'read' CHECK (access IN ('read', 'readwrite')),
  skills JSONB NOT NULL DEFAULT '[]',
  metadata JSONB NOT NULL DEFAULT '{}',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE scopes (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  token TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL UNIQUE,
  description TEXT,
  scope JSONB NOT NULL DEFAULT '{}',
  metadata JSONB NOT NULL DEFAULT '{}',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE profiles (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  token TEXT NOT NULL UNIQUE,
  actor_id INTEGER NOT NULL REFERENCES actors(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  metadata JSONB NOT NULL DEFAULT '{}',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  last_used_at TIMESTAMPTZ,
  UNIQUE (actor_id, name)
);

CREATE TABLE sessions (
  id TEXT PRIMARY KEY,
  user_id INTEGER REFERENCES actors(id) ON DELETE SET NULL,
  agent_id INTEGER NOT NULL REFERENCES actors(id) ON DELETE RESTRICT,
  profile_id INTEGER REFERENCES profiles(id) ON DELETE SET NULL,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  state TEXT NOT NULL DEFAULT 'open' CHECK (state IN ('open', 'closed', 'archived')),
  status TEXT NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending', 'planning', 'running', 'completed', 'failed', 'cancelled')),
  system_prompt TEXT,
  summary TEXT,
  traits JSONB NOT NULL DEFAULT '[]',
  scope JSONB,
  scope_id INTEGER REFERENCES scopes(id) ON DELETE SET NULL,
  metadata JSONB NOT NULL DEFAULT '{}',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  started_at TIMESTAMPTZ,
  completed_at TIMESTAMPTZ,
  ended_at TIMESTAMPTZ
);

CREATE TABLE provider_sessions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id TEXT NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
  provider TEXT NOT NULL CHECK (provider IN ('claude', 'codex', 'opencode')),
  provider_session_id TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  ended_at TIMESTAMPTZ
);

CREATE TABLE messages (
  id TEXT PRIMARY KEY,
  session_id TEXT REFERENCES sessions(id) ON DELETE CASCADE,
  provider_session_id TEXT,
  type TEXT NOT NULL CHECK (type IN ('message', 'tool_call')),
  sequence INTEGER NOT NULL DEFAULT 0 CHECK (sequence >= 0),
  role TEXT CHECK (role IN ('user', 'assistant', 'system')),
  content JSONB,
  name TEXT,
  input JSONB,
  result JSONB,
  metadata JSONB NOT NULL DEFAULT '{}',
  content_text TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE repos (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  path TEXT NOT NULL UNIQUE,
  color TEXT,
  sort_order INTEGER NOT NULL DEFAULT 0,
  metadata JSONB NOT NULL DEFAULT '{}',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE artifacts (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  token TEXT NOT NULL UNIQUE,
  type TEXT NOT NULL DEFAULT 'artifact',
  file_path TEXT,
  version INTEGER NOT NULL DEFAULT 1 CHECK (version > 0),
  created_by_session_id TEXT REFERENCES sessions(id) ON DELETE SET NULL,
  updated_by_session_id TEXT REFERENCES sessions(id) ON DELETE SET NULL,
  metadata JSONB NOT NULL DEFAULT '{}',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE settings (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  scope TEXT NOT NULL,
  scope_id TEXT,
  key TEXT NOT NULL,
  value JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE OR REPLACE FUNCTION update_message_content_text() RETURNS TRIGGER
LANGUAGE plpgsql AS $$
BEGIN
  NEW.content_text := (
    SELECT string_agg(element->>'text', ' ')
    FROM jsonb_array_elements(
      CASE WHEN jsonb_typeof(NEW.content) = 'array' THEN NEW.content ELSE '[]'::jsonb END
    ) AS element
    WHERE element->>'type' = 'text'
  );
  RETURN NEW;
END;
$$;

CREATE TRIGGER messages_content_text
  BEFORE INSERT OR UPDATE OF content ON messages
  FOR EACH ROW EXECUTE FUNCTION update_message_content_text();

CREATE INDEX idx_actors_type ON actors(type);
CREATE INDEX idx_profiles_actor_name ON profiles(actor_id, name);
CREATE INDEX idx_sessions_active ON sessions(active) WHERE active = TRUE;
CREATE INDEX idx_sessions_created_at ON sessions(created_at DESC);
CREATE INDEX idx_sessions_state_status ON sessions(state, status);
CREATE INDEX idx_sessions_profile_id ON sessions(profile_id);
CREATE INDEX idx_provider_sessions_session_id ON provider_sessions(session_id, created_at DESC);
CREATE INDEX idx_provider_sessions_provider_id ON provider_sessions(provider, provider_session_id);
CREATE INDEX idx_messages_session_sequence ON messages(session_id, sequence);
CREATE INDEX idx_messages_provider_session_id ON messages(provider_session_id);
CREATE INDEX idx_messages_created_at ON messages(created_at);
CREATE INDEX idx_messages_content_trgm ON messages USING GIN (content_text gin_trgm_ops);
CREATE INDEX idx_repos_sort_order ON repos(sort_order, name);
CREATE UNIQUE INDEX idx_artifacts_path ON artifacts(file_path) WHERE file_path IS NOT NULL;
CREATE INDEX idx_artifacts_type_updated ON artifacts(type, updated_at DESC);
CREATE UNIQUE INDEX idx_settings_global_key ON settings(scope, key) WHERE scope_id IS NULL;
CREATE UNIQUE INDEX idx_settings_scoped_key ON settings(scope, scope_id, key) WHERE scope_id IS NOT NULL;
