-- Providers and models as first-class rows, plus per-message model provenance.
--
-- WHY: today a message records no model at all. `messages` has no actor FK and
-- no model column, session-level metadata was only ever written by the
-- API/web path (1 of 383 sessions carried it), and `actors.models` — the
-- earlier attempt at this — was written by seed and read by nothing (dropped
-- in 019). So "which messages came from Opus 5 vs GPT-5.6" is unanswerable.
--
-- The FK on messages.model_id is what keeps this table honest: unlike
-- actors.models, an incorrect entry now surfaces as an insert error rather
-- than silent staleness. Writers upsert unknown models on first sight, so the
-- constraint never blocks a session running a model newer than the catalog.

CREATE TABLE IF NOT EXISTS providers (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  key TEXT NOT NULL UNIQUE,
  label TEXT NOT NULL,
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  metadata JSONB NOT NULL DEFAULT '{}',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Model ids are only unique WITHIN a provider: `gpt-5.3-codex` is offered by
-- both codex and cursor, and claude-opus-5 by both claude and opencode (as
-- anthropic/claude-opus-5). Hence the composite natural key — a bare model_id
-- could not distinguish an Opus 5 turn via Cursor from one via the Claude CLI,
-- which is exactly the attribution this table exists to provide.
CREATE TABLE IF NOT EXISTS models (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  provider_id INTEGER NOT NULL REFERENCES providers(id) ON DELETE CASCADE,
  model_id TEXT NOT NULL,
  label TEXT NOT NULL,
  metadata JSONB NOT NULL DEFAULT '{}',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (provider_id, model_id)
);

-- Nullable, and it must stay that way. 43k existing messages predate any
-- provenance recording and can never be backfilled (the model appears nowhere
-- in their payloads). "Provider chose its own default" is also an ongoing,
-- legitimate state now that every provider has `default: null`. A sentinel
-- row would assert a model that never ran.
--
-- ON DELETE SET NULL rather than RESTRICT: pruning a model from the catalog
-- must not be blocked by, or destroy, historical messages.
ALTER TABLE messages ADD COLUMN IF NOT EXISTS model_id INTEGER
  REFERENCES models(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS idx_messages_model_id
  ON messages (model_id) WHERE model_id IS NOT NULL;
